import { useCallback, useEffect, useState } from 'react'
import { Plus, Pencil, Trash2 } from 'lucide-react'
import { Card, Btn, Modal, Field, Table, inputCls } from '@/components/admin'
import { apiRequest, jsonBody } from '@/api/client'
import type { TagView } from '@/api/types'

const PALETTE=['#2dd4bf','#a78bfa','#22d3ee','#818cf8','#f472b6','#34d399','#fbbf24','#fb7185','#38bdf8','#4ade80']

export default function Tags() {
  const [tags,setTags]=useState<TagView[]>([]), [editing,setEditing]=useState<TagView|null>(null), [creating,setCreating]=useState(false), [removing,setRemoving]=useState<TagView|null>(null), [error,setError]=useState('')
  const load=useCallback(()=>apiRequest<TagView[]>('/api/admin/tags').then(setTags).catch(reason=>setError(reason.message)),[])
  useEffect(()=>{load()},[load])
  const save=async(name:string,color:string)=>{ setError(''); try { const path=editing?`/api/admin/tags/${editing.id}`:'/api/admin/tags'; await apiRequest(path,{method:editing?'PUT':'POST',...jsonBody({name,color})}); setEditing(null);setCreating(false);load() } catch(reason){setError((reason as Error).message)} }
  const remove=async()=>{ if(!removing)return; try{await apiRequest(`/api/admin/tags/${removing.id}?force=true`,{method:'DELETE'});setRemoving(null);load()}catch(reason){setError((reason as Error).message)} }
  return <div className="space-y-4">{error&&<p className="rounded-lg border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<div className="flex items-center justify-between"><p className="text-sm text-white/45">共 {tags.length} 个标签</p><Btn variant="primary" className="flex items-center gap-1.5" onClick={()=>setCreating(true)}><Plus size={15}/>新建标签</Btn></div><Card><Table head={['标签','颜色','文章数','操作']}>{tags.map(tag=><tr key={tag.id} className="data-row border-b border-white/[.05]"><td className="px-5 py-3.5"><span className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs" style={{borderColor:`${tag.color}55`,color:tag.color,background:`${tag.color}14`}}><span className="h-1.5 w-1.5 rounded-full" style={{background:tag.color}}/>{tag.name}</span></td><td className="px-5 py-3.5 font-mono2 text-xs text-white/45">{tag.color}</td><td className="px-5 py-3.5 font-mono2 text-xs text-white/55">{tag.articleCount} 篇</td><td className="px-5 py-3.5"><button aria-label="编辑" onClick={()=>setEditing(tag)} className="p-1.5 text-white/45 hover:text-teal-300"><Pencil size={15}/></button><button aria-label="删除" onClick={()=>setRemoving(tag)} className="p-1.5 text-white/45 hover:text-red-300"><Trash2 size={15}/></button></td></tr>)}</Table></Card>{(creating||editing)&&<TagForm key={editing?.id??'new'} initial={editing??{name:'',color:PALETTE[0]}} onClose={()=>{setCreating(false);setEditing(null)}} onSave={save}/>}<Modal open={!!removing} title="删除标签" onClose={()=>setRemoving(null)} footer={<><Btn onClick={()=>setRemoving(null)}>取消</Btn><Btn variant="danger" onClick={remove}>确认删除</Btn></>}><p className="text-sm text-white/65">删除「<span className="text-white">{removing?.name}</span>」后，{removing?.articleCount} 篇文章将失去该标签。</p></Modal></div>
}

function TagForm({initial,onClose,onSave}:{initial:{name:string;color:string};onClose:()=>void;onSave:(name:string,color:string)=>void}){const[name,setName]=useState(initial.name),[color,setColor]=useState(initial.color);return <Modal open title={initial.name?'编辑标签':'新建标签'} onClose={onClose} footer={<><Btn onClick={onClose}>取消</Btn><Btn variant="primary" onClick={()=>name.trim()&&onSave(name.trim(),color)}>保存</Btn></>}><div className="space-y-4"><Field label="标签名"><input value={name} onChange={e=>setName(e.target.value)} className={inputCls}/></Field><Field label="颜色"><div className="flex flex-wrap gap-2.5">{PALETTE.map(item=><button type="button" aria-label={item} key={item} onClick={()=>setColor(item)} className={`h-8 w-8 rounded-full ${color===item?'ring-2 ring-white/60 ring-offset-2 ring-offset-[#12121c]':''}`} style={{background:item}}/>)}</div></Field></div></Modal>}
